name: autogluon_py3
dependencies:
- python=3.7
- graphviz
- pip:
  - jupyter-sphinx>=0.2.2
  - gluonnlp==0.8.1
  - https://autogluon-kdd-mxnet-wheels.s3-accelerate.amazonaws.com/mxnet_cu101-1.7.0b20200822-py2.py3-none-manylinux2014_x86_64.whl
  - portalocker
  - nose
  - docutils
  - mu-notedown
  - flake8
