name: autogluon_py3
dependencies:
- python=3.7
- graphviz
- pip:
  - --find-links https://sxjscience.github.io/KDD2020/
  - jupyter-sphinx>=0.2.2
  - mxnet_cu100>=1.7.0b20200713, <2.0.0
  - gluonnlp==0.8.1
  - https://autogluon-kdd-mxnet-wheels.s3.amazonaws.com/autogluon_contrib_nlp-1.0.0.dev0b20200804-py3-none-any.whl
  - portalocker
  - nose
  - docutils
  - mu-notedown
  - flake8
